### ISSUE TITLE
[Feature] make `mmcls.apis.inference.init_model` arg `config` accept `PathLike`

### ISSUE THREAD

**Issue by hubutui** [open-mmlab/mmpretrain#1235]
### Branch

master branch (0.24 or other 0.x version)

### Describe the feature

Currently, https://github.com/open-mmlab/mmclassification/blob/578c035d5c414deb194285766cb098863b21898a/mmcls/apis/inference.py#L27-L31 checks if `config` is `str`, while `mmcv.Config.fromfile`  accept `PathLike`. See also https://github.com/open-mmlab/mmcv/pull/91.

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by Ezra-Yu** [comment]
Thank you for your suggestion, welcome to implement this and propose a PR refer to this [page](https://mmclassification.readthedocs.io/en/latest/community/CONTRIBUTING.html).

which will be like the following:
```python
from pathlib import Path
 if isinstance(config, (str, Path)): 
     config = mmcv.Config.fromfile(config) 
 else: 
     raise TypeError('config must be a filename, Config object or a file-like object., ' 
                     f'but got {type(config)}') 

```

**Comment by hubutui** [comment]
Yes, it only needs minor changes. PR is welcome. Sorry, I'm busy with other projects.
