### ISSUE TITLE
[Bug] Wrong URL of EfficientNet-B2 (RA + NoisyStudent) model

### ISSUE THREAD

**Issue by okotaku** [open-mmlab/mmpretrain#1237]
### Branch

1.x branch (1.0.0rc2 or other 1.x version)

### Describe the bug

https://github.com/open-mmlab/mmclassification/blob/dev-1.x/configs/efficientnet/README.md

EfficientNet-B2 (RA + NoisyStudent) model url is wrong. Now it is `https://download.openmmlab.com/mmclassification/v0/efficientnet/efficientnet-b1_3rdparty-ra-noisystudent_in1k_20221103-756bcbc0.pth`.

### Environment

None

**Comment by Ezra-Yu** [comment]
Thanks for your report, I will fix that.

**Comment by Ezra-Yu** [comment]
has fixed in pretrain
