### ISSUE TITLE
[Feature] make v1.0.0rc7 as pre-release

### ISSUE THREAD

**Issue by hubutui** [open-mmlab/mmpretrain#1468]
### Describe the feature

If it's not a release, mark it as pre-release, thanks. https://github.com/open-mmlab/mmpretrain/releases/tag/v1.0.0rc7

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by Ezra-Yu** [comment]
All the releases with 'rc'(release-condidate) in the tag are pre-releases.

**Comment by hubutui** [comment]
@Ezra-Yu Yes, then just mark it as pre-release. See also https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release, step 10.
