### ISSUE TITLE
Label attribute mentioned in some docs is 'img_label', but 'gt_label' is actually used in the code

### ISSUE THREAD

**Issue by ravenmk3** [open-mmlab/mmpretrain#1479]
### 分支

main 分支 (mmpretrain 版本)

### 描述该错误

Label attribute mentioned in some docs is 'img_label', but 'gt_label' is actually used in the code

https://github.com/open-mmlab/mmpretrain/search?q=img_label
https://github.com/open-mmlab/mmpretrain/search?q=gt_label

### 环境信息

None

**Comment by Ezra-Yu** [comment]
Using **'gt_label'**  is correct as in the code, Could help us create PR and fix the doc typo of 'img_label'?
