### ISSUE TITLE
[Bug] RuntimeError: result type Float can't be cast to the desired output type Long

### ISSUE THREAD

**Issue by boxbox-0427** [open-mmlab/mmpretrain#1495]
### Branch

main branch (mmpretrain version)

### Describe the bug

This problem happend when I tried to run `multi-label` training task.

I implemented a new datatype, and with json format  data, like:
```
  "data_list": [
    {
      "img_path": "black_dress_0.jpg",
      "img_label": [
        0,
        4
      ]
```

Actually, I have no idea how to organize the data and datatype with `mmpretrain` because there is less doc about it. So could u please write more doc about it ? The `multi-label` task, together with `multi-task`.

Thanks!

### Environment

Does not matter

### Other information

More documentation is needed about `multi-label` and `multi-task`

**Comment by Ezra-Yu** [comment]
Thank you very much for your feedback, we will start working on additional tutorials in this area right away.

Can you provide the full error message of the reported error as well? So I can locate the error location faster.

**Comment by Ezra-Yu** [comment]
Do you use LabelSmooth, MixUp, or CutMix?

**Comment by boxbox-0427** [comment]
No, and I just changed the code from
```
    loss = F.binary_cross_entropy_with_logits(
        pred,
        label,
        weight=class_weight,
        pos_weight=pos_weight,
        reduction='none')
```
to
```
    loss = F.binary_cross_entropy_with_logits(
        pred,
        label.float(),
        weight=class_weight,
        pos_weight=pos_weight,
        reduction='none')
```
And it works with this problem. However another error arises. So I think it's better to wait for your tutorials.

**Comment by Ezra-Yu** [comment]
In our experiment, we can run the VOC-multi-label classification task after fixing the error. https://github.com/open-mmlab/mmpretrain/pull/1499

**Comment by boxbox-0427** [comment]
Maybe this error occured due to my wrong `config` file or `dataset type`, I changed the type into `voc`, and now it works, thanks!

And still wait for your tutorial docs about `multi-label` or `multi-task`!

**Comment by boxbox-0427** [comment]
Now it can run few epochs, but don't know whether the error would show up again.....

I think it's related to my dataset, and you can close this issue now, THANKS!

Wait for your docs and tutorials!!!

**Comment by boxbox-0427** [comment]
Well.... I find the reason which caused this error.

The img_bytes of some imgs are like `b'GIFxxxxx...'`, whose suffix is 'jpg'. JUST DELETE THEM.

These imgs are downloaded from network, and now my heart is broken.

**Comment by Ezra-Yu** [comment]
```
File "D:\codeMaker\conda\envs\detection\lib\site-packages\mmcv\transforms\loading.py", line 112, in transform
    results['img_shape'] = img.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
```

This error should be raised to be a little clearer, where there are some errors in reading the specific image. Then print the image path.

**Comment by boxbox-0427** [comment]
Sure, I just deleted those imgs, and it now works!
