### ISSUE TITLE
[Bug] image_demo.py: error: unrecognized arguments: /--out-file vis_results.jpg /--draw-heatmap

### ISSUE THREAD

**Issue by Ezreal0211** [open-mmlab/mmpretrain#1496]
### Branch

main branch (mmpretrain version)

### Describe the bug

when I installed the mmpose，I want to verify if my installation was successful.So I followed the Verification steps.The first step is ok,(mim download mmpose --config td-hm_hrnet-w48_8xb32-210e_coco-256x192  --dest .)
but the second step gave me this error.
(python demo/image_demo.py \
    tests/data/coco/000000000785.jpg \
    td-hm_hrnet-w48_8xb32-210e_coco-256x192.py \
    hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth \
    --out-file vis_results.jpg \
    --draw-heatmap)
I don't know why.Please help me and thanks for everyone!(I used the newest installation of mmpose)

### Environment

All environments are configured according to the latest MMPOSE installation tutorial.

**Comment by Ezra-Yu** [comment]
there are no in `--out-file` and `--draw-heatmap` in https://github.com/open-mmlab/mmpretrain/blob/e80418a424aaefb81c95df458216bb3e9af246c4/demo/image_demo.py#L11-L23

**Comment by Ezreal0211** [comment]
So what command should I use to test if the installation of mmpose was successful？Thanks！

**Comment by Ezra-Yu** [comment]
you should cd into in mmpose folder and then run 
```
python demo/image_demo.py
tests/data/coco/000000000785.jpg
td-hm_hrnet-w48_8xb32-210e_coco-256x192.py
hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth
--out-file vis_results.jpg
--draw-heatmap
```

and this issue should be created in `mmpose` repo.

**Comment by Ezreal0211** [comment]
Thanks，But this is the error that occurred when I switched to the mmpose folder and used this command，so what should I do next？

**Comment by Ezra-Yu** [comment]
in $MMPOSE dir. run
```
python demo/image_demo.py -h
```

check-in help information,

**Comment by Ezreal0211** [comment]
Thanks for your help!Sorry to waste so much of your time.

**Comment by Limbo844** [comment]
I have this problem too, but I entered Ezra's last guide, what should I do then? Can you tell me how to solve the problem?
