### ISSUE TITLE
[Bug] MMCV==2.0.0 is used but incompatible. Please install mmcv>=1.3.17, <=1.8.0.

### ISSUE THREAD

**Issue by shichen-wang** [open-mmlab/mmpretrain#1508]
### Branch

main branch (mmpretrain version)

### Describe the bug

When I run demo code :  python demo/image_demo.py demo/demo.JPEG resnet18_8xb32_in1k --device cpu
I get this error AssertionError: MMCV==2.0.0 is used but incompatible. Please install mmcv>=1.3.17, <=1.8.0.
then I try to use mmcv=1.3.17 and mmcv=1.7.1
I get another error  AssertionError: MMCV==1.3.7 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.///AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.
how can i fix this

### Environment

I cant do this 
I also get AssertionError: MMCV==1.3.7 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

**Comment by Ezra-Yu** [comment]
run
```
pip install openmim
mim uninstall mmcv
mim install mmcv>=2.0.0rc4
```

**Comment by Jay-Humor** [comment]
> ### Branch
> main branch (mmpretrain version)
> 
> ### Describe the bug
> When I run demo code : python demo/image_demo.py demo/demo.JPEG resnet18_8xb32_in1k --device cpu I get this error AssertionError: MMCV==2.0.0 is used but incompatible. Please install mmcv>=1.3.17, <=1.8.0. then I try to use mmcv=1.3.17 and mmcv=1.7.1 I get another error AssertionError: MMCV==1.3.7 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.///AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0. how can i fix this
> 
> ### Environment
> I cant do this I also get AssertionError: MMCV==1.3.7 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.
> 
> ### Other information
> _No response_

I think this maybe using mmcv-full, uninstall it will become AssertionError: MMCV==2.0.0 is used but incompatible. Please install mmcv>=1.3.17, <=1.8.0.

**Comment by Ezra-Yu** [comment]
run 
```
python -c "import mmpretrain.utils;import pprint;pprint.pp(dict(mmpretrain.utils.collect_env()))"
```
and show your environment.

**Comment by Jay-Humor** [comment]
I got it, this is because some other import like mmdet in old version, just uninstall all related mm libs and install them again

**Comment by ya-92626** [comment]
> 我明白了，这是因为其他一些导入，如旧版本中的 mmdet，只需卸载所有相关的 mm 库并重新安装它们

How do you operate it, please? What version of the mm package was reinstalled

**Comment by Jay-Humor** [comment]
> > 我明白了，这是因为其他一些导入，如旧版本中的 mmdet，只需卸载所有相关的 mm 库并重新安装它们
> 
> 
> 
> How do you operate it, please? What version of the mm package was reinstalled

just remove all mmlab libraries，using like pip uninstall mm*？

**Comment by ya-92626** [comment]
> > > 我明白了，这是因为其他一些导入，如旧版本中的 mmdet，只需卸载所有相关的 mm 库并重新安装它们
> > 
> > 
> > 请问您如何操作它？重新安装了哪个版本的 mm 软件包
> 
> 只需删除所有 mmlab 库，使用 pip 卸载 mm*？
What version of the mmcv package was reinstalled?

**Comment by Jay-Humor** [comment]
> > > > 我明白了，这是因为其他一些导入，如旧版本中的 mmdet，只需卸载所有相关的 mm 库并重新安装它们
> 
> > > 
> 
> > > 
> 
> > > 请问您如何操作它？重新安装了哪个版本的 mm 软件包
> 
> > 
> 
> > 只需删除所有 mmlab 库，使用 pip 卸载 mm*？
> 
> What version of the mmcv package was reinstalled?
> 
> 

all versions

**Comment by CaMi1le** [comment]
> I got it, this is because some other import like mmdet in old version, just uninstall all related mm libs and install them again

In my condition the torch version matters, double check your torch version is the right one.
