### ISSUE TITLE
[Feature] Real-time Generated Dataset

### ISSUE THREAD

**Issue by Jay-Humor** [open-mmlab/mmpretrain#1515]
### Describe the feature

It's inconvenient when I want to generate my dataset using models like GAN or other generative models. Are there any solutions?

I want to generate an image based on the last iter results as input in the next iter.

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by Ezra-Yu** [comment]
I'm very sorry, but this is the first time I've come across such a requirement, and I am curious if such a dataset is for training or for testing.

**Comment by Jay-Humor** [comment]
It's for training, I want to train a open-dataset network

**Comment by Jay-Humor** [comment]
Are there any method that can build a network using mmlab modules from config file? I mean networks just like be in pure pytorch, I just want the convenient model build methods, and it just use the forward pass.

**Comment by Ezra-Yu** [comment]
1. **`list_models`**

`list_models` supports fuzzy matching, you can use **\*** to match any character.

```
>>> from mmpretrain import list_models
>>> list_models("*clip-openai")
['vit-base-p16_clip-openai-in12k-pre_3rdparty_in1k',
 'vit-base-p16_clip-openai-in12k-pre_3rdparty_in1k-384px',
 'vit-base-p16_clip-openai-pre_3rdparty_in1k',
 'vit-base-p16_clip-openai-pre_3rdparty_in1k-384px',
 'vit-base-p32_clip-openai-in12k-pre_3rdparty_in1k-384px',
 'vit-base-p32_clip-openai-pre_3rdparty_in1k']
```
```
>>> list_models("*convnext-b*21k")
['convnext-base_3rdparty_in21k',
 'convnext-base_in21k-pre-3rdparty_in1k-384px',
 'convnext-base_in21k-pre_3rdparty_in1k']
```

2. **`get_model`**

`get_model` can get the model from model names

```
>>> from mmpretrain import get_model
>>> init_model = get_model("convnext-base_in21k-pre_3rdparty_in1k")
>>> pretrained_model = get_model("convnext-base_in21k-pre_3rdparty_in1k", pretrained=True)
# Do the froward
>>> import torch
>>> x = torch.rand((1, 3, 224, 224))
>>> y = pretrained_model(x)
>>> print(type(y), y.shape)
<class 'torch.Tensor'> torch.Size([1, 1000])
```

**Comment by Jay-Humor** [comment]
Thanks for you suggestion!
