### ISSUE TITLE
[Bug] The model and loaded state dict do not match exactly in beitv2

### ISSUE THREAD

**Issue by slowpokeJeavan** [open-mmlab/mmpretrain#1527]
### Branch

main branch (mmpretrain version)

### Describe the bug

Seems that there is some mismatchings between model file and ckpt weights in BEITV2
'''python
from mmpretrain import get_model
beitv2_vitb16 = get_model('beitv2_beit-base-p16_8xb256-amp-coslr-300e_in1k', pretrained=True).backbone
'''
'''shell
The model and loaded state dict do not match exactly

missing keys in source state_dict: backbone.ln2.weight, backbone.ln2.bias
'''

### Environment

'PyTorch': '1.13.0+cu117',
 'TorchVision': '0.14.0+cu117',
 'OpenCV': '4.7.0',
 'MMEngine': '0.7.2',
 'MMCV': '2.0.0',
 'MMPreTrain': '1.0.0rc7+'}

**Comment by fangyixiao18** [comment]
Thanks for your reporting, we miss the `out_type='raw'` in the config

**Comment by slowpokeJeavan** [comment]
> Thanks for your reporting, we miss the `out_type='raw'` in the config

could it influence the performance?I mean if the unmatched parameters is random initialized?
How can I fixed it?
Thank you for your great work in implementing these latest models in open source!

**Comment by fangyixiao18** [comment]
> > Thanks for your reporting, we miss the `out_type='raw'` in the config
> 
> could it influence the performance?I mean if the unmatched parameters is random initialized? How can I fixed it? Thank you for your great work in implementing these latest models in open source!

You could use `dev` branch, we have fixed it. 
As for the influence on the performance, we are not sure about it, I guess it might have around 0.1~0.2 differences or just the same.
