### ISSUE TITLE
[Bug] AttributeError: 'ConfigDict' object has no attribute 'data_preprocessor' when convert vision_transformer to ONNX

### ISSUE THREAD

**Issue by biyuehuang** [open-mmlab/mmpretrain#1553]
### Branch

main branch (mmpretrain version)

### Describe the bug

Can't convert vision_transformer model to ONNX.

$ python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmocr/text-recognition/text-recognition_onnxruntime_dynamic.py \
    mmpretrain/configs/vision_transformer/vit-base-p32_64xb64_in1k-384px.py \
    vit-base-p32_in21k-pre-3rdparty_ft-64xb64_in1k-384_20210928-9cea8599.pth \
    mmdetection/demo/demo.mp4 \
    --work-dir model_onnx/vit/ \
    --device cpu \
    --dump-info

05/08 15:48:29 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
05/08 15:48:29 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "mmocr_tasks" registry tree. As a workaround, the current "mmocr_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
05/08 15:48:29 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
/home/a380/Downloads/kiwi/MTL/mmocr/mmocr/utils/setup_env.py:34: UserWarning: The current default scope "mmpretrain" is not "mmocr", `register_all_modules` will force the currentdefault scope to be "mmocr". If this is not expected, please set `init_default_scope=False`.
  warnings.warn('The current default scope '
Traceback (most recent call last):
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmengine/config/config.py", line 52, in __getattr__
    value = super().__getattr__(name)
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/addict/addict.py", line 67, in __getattr__
    return self.__getitem__(item)
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmengine/config/config.py", line 48, in __missing__
    raise KeyError(name)
KeyError: 'data_preprocessor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mmdeploy/tools/deploy.py", line 335, in <module>
    main()
  File "mmdeploy/tools/deploy.py", line 129, in main
    export2SDK(
  File "/home/a380/Downloads/MTL/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 349, in export2SDK
    pipeline_info = get_pipeline(deploy_cfg, model_cfg, work_dir, device)
  File "/home/a380/Downloads/MTL/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 282, in get_pipeline
    preprocess = get_preprocess(deploy_cfg, model_cfg, device=device)
  File "/home/a380/Downloads/MTL/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 197, in get_preprocess
    transforms = task_processor.get_preprocess()
  File "/home/a380/Downloads/MTL/mmdeploy/mmdeploy/codebase/mmocr/deploy/text_recognition.py", line 236, in get_preprocess
    data_preprocessor = model_cfg.model.data_preprocessor
  File "/home/a380/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmengine/config/config.py", line 54, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ConfigDict' object has no attribute 'data_preprocessor'

### Environment

git clone main mmdeploy and build it.
https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/01-how-to-build/linux-x86_64.md

**Comment by biyuehuang** [comment]
@RunningLeon Hi Leon, can you give some suggestion?

**Comment by RunningLeon** [comment]
> @RunningLeon Hi Leon, can you give some suggestion?


Hi, it seems that wrong deploy config (`mmdeploy/configs/mmocr/text-recognition/text-recognition_onnxruntime_dynamic.p`) is used. Pls. use latest `main` branch of mmdeploy and this deploy config: https://github.com/open-mmlab/mmdeploy/blob/main/configs/mmpretrain/classification_onnxruntime_dynamic.py

**Comment by biyuehuang** [comment]
@RunningLeon 

$ python mmdeploy/tools/deploy.py \
    mmdeploy/configs/ mmpretrain/classification_onnxruntime_dynamic.py \
    mmpretrain/configs/vision_transformer/vit-base-p32_64xb64_in1k-384px.py \
    vit-base-p32_in21k-pre-3rdparty_ft-64xb64_in1k-384_20210928-9cea8599.pth \
    mmdetection/demo/demo.mp4 \
    --work-dir model_onnx/vit/ \
    --device cpu \
    --dump-info

usage: deploy.py [-h] [--test-img TEST_IMG [TEST_IMG ...]] [--work-dir WORK_DIR] [--calib-dataset-cfg CALIB_DATASET_CFG] [--device DEVICE]
                 [--log-level {CRITICAL,FATAL,ERROR,WARN,WARNING,INFO,DEBUG,NOTSET}] [--show] [--dump-info] [--quant-image-dir QUANT_IMAGE_DIR] [--quant] [--uri URI]
                 deploy_cfg model_cfg checkpoint img
deploy.py: error: unrecognized arguments: mmdetection/demo/demo.mp4
(mmdeploy) a380@a380-System-Product-Name:~/Downloads/kiwi/MTL$
(mmdeploy) a380@a380-System-Product-Name:~/Downloads/kiwi/MTL$ python mmdeploy/tools/deploy.py     mmdeploy/configs/ mmpretrain/classification_onnxruntime_dynamic.py     mmpretrain/configs/vision_transformer/vit-base-p32_64xb64_in1k-384px.py     vit-base-p32_in21k-pre-3rdparty_ft-64xb64_in1k-384_20210928-9cea8599.pth     mmdetection/demo/demo.jpg     --work-dir model_onnx/vit/     --device cpu     --dump-info
usage: deploy.py [-h] [--test-img TEST_IMG [TEST_IMG ...]] [--work-dir WORK_DIR] [--calib-dataset-cfg CALIB_DATASET_CFG] [--device DEVICE]
                 [--log-level {CRITICAL,FATAL,ERROR,WARN,WARNING,INFO,DEBUG,NOTSET}] [--show] [--dump-info] [--quant-image-dir QUANT_IMAGE_DIR] [--quant] [--uri URI]
                 deploy_cfg model_cfg checkpoint img
deploy.py: error: unrecognized arguments: mmdetection/demo/demo.jpg

**Comment by RunningLeon** [comment]
@biyuehuang hi, input_img should be image not video(`mmdetection/demo/demo.mp4`). Pls. refer to [here ](https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmpretrain.html#convert-model) for example.

**Comment by KiwiHana** [comment]
> $ python mmdeploy/tools/deploy.py mmdeploy/configs/ mmpretrain/classification_onnxruntime_dynamic.py mmpretrain/configs/vision_transformer/vit-base-p32_64xb64_in1k-384px.py vit-base-p32_in21k-pre-3rdparty_ft-64xb64_in1k-384_20210928-9cea8599.pth mmdetection/demo/demo.jpg --work-dir model_onnx/vit/ --device cpu --dump-info
> usage: deploy.py [-h] [--test-img TEST_IMG [TEST_IMG ...]] [--work-dir WORK_DIR] [--calib-dataset-cfg CALIB_DATASET_CFG] [--device DEVICE]
> [--log-level {CRITICAL,FATAL,ERROR,WARN,WARNING,INFO,DEBUG,NOTSET}] [--show] [--dump-info] [--quant-image-dir QUANT_IMAGE_DIR] [--quant] [--uri URI]
> deploy_cfg model_cfg checkpoint img
> deploy.py: error: unrecognized arguments: mmdetection/demo/demo.jpg

**Comment by RunningLeon** [comment]
@KiwiHana Hi, have you changed anything in model config? could you try with the official model config and ckpt provided by mmpretrain at first?

**Comment by biyuehuang** [comment]
> @biyuehuang hi, input_img should be image not video(`mmdetection/demo/demo.mp4`). Pls. refer to [here ](https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmpretrain.html#convert-model) for example.

Yes, you are right!
python mmdeploy/tools/deploy.py
mmdeploy/configs/mmpretrain/classification_onnxruntime_dynamic.py
mmpretrain/configs/vision_transformer/vit-base-p32_64xb64_in1k-384px.py
vit-base-p32_in21k-pre-3rdparty_ft-64xb64_in1k-384_20210928-9cea8599.pth
mmdetection/demo/demo.jpg
--work-dir model_onnx/vit/
--device cpu
--dump-info
