### ISSUE TITLE
[Bug] TypeError: __init__() got an unexpected keyword argument 'show'

### ISSUE THREAD

**Issue by guneetmutreja** [open-mmlab/mmpretrain#1589]
### Branch

mmcls-1.x branch (v1.0.0rc6 or other 1.x version)

### Describe the bug

'show' argument in inference model method throws unexpected keyword argument error.

```python
from mmpretrain import inference_model
image = 'https://github.com/open-mmlab/mmpretrain/raw/main/demo/demo.JPEG'
# If you have no graphical interface, please set `show=False`
result = inference_model('resnet50_8xb32_in1k', image, show=True)
print(result['pred_class'])
```

## Error message
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb32_in1k_20210831-ea4938fc.pth

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_1817952/209455165.py in <cell line: 4>()
      2 image = 'https://github.com/open-mmlab/mmpretrain/raw/main/demo/demo.JPEG'
      3 # If you have no graphical interface, please set `show=False`
----> 4 result = inference_model('resnet50_8xb32_in1k', image, show=True)
      5 print(result['pred_class'])

~/Documents/mmpretrain/mmpretrain/apis/model.py in inference_model(model, input_, **kwargs)
    324 
    325     if isinstance(model, mmpretrain.models.ImageClassifier):
--> 326         inferencer = ImageClassificationInferencer(model, **kwargs)
    327     elif isinstance(model, mmpretrain.models.ImageToImageRetriever):
    328         inferencer = ImageRetrievalInferencer(model, **kwargs)

TypeError: __init__() got an unexpected keyword argument 'show'

### Environment

``` python
{'sys.platform': 'linux',
 'Python': '3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]',
 'CUDA available': True,
 'numpy_random_seed': 2147483648,
 'GPU 0': 'NVIDIA TITAN RTX',
 'CUDA_HOME': '/usr/local/cuda',
 'NVCC': 'Cuda compilation tools, release 11.0, V11.0.194',
 'GCC': 'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0',
 'PyTorch': '1.8.2',
 'TorchVision': '0.9.2',
 'OpenCV': '4.7.0',
 'MMEngine': '0.7.3',
 'MMCV': '2.0.0rc4',
 'MMPreTrain': '1.0.0rc7+e80418a'}
```

**Comment by mzr1996** [comment]
Please update your MMPretrain to the latest `1.0.0rc8`, and the `inference_model` will accept `show` argument

**Comment by guneetmutreja** [comment]
@mzr1996 Thank you, updating mmpretrain version to the latest helped resolve the issue.
