### ISSUE TITLE
[Bug] ConvNeXts showcasing poor results

### ISSUE THREAD

**Issue by guneetmutreja** [open-mmlab/mmpretrain#1590]
### Branch

mmcls-1.x branch (v1.0.0rc6 or other 1.x version)

### Describe the bug

Tried several pretrained convNeXt backbones for inferencing but the results are poor.

## Code to reproduce
``` python
from mmpretrain import ImageClassificationInferencer
inferencer = ImageClassificationInferencer('convnext-small_32xb128_in1k')
inferencer('data/n01443537_11251.JPEG', show=True)

```

## Results
``` python
'pred_label': 744,
 'pred_score': 0.029210692271590233,
 'pred_class': 'projectile, missile'}]
```

## Image used
 https://storage.googleapis.com/kagglesdsdata/datasets/547506/998277/imagenet-mini/train/n01443537/n01443537_11251.JPEG?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20230523%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230523T160438Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=5c7e6fa40edbb710ff01a2b8baf23cfc71f02cc7b2367ab96e06fdab057f855c704c746c8545caad6c1fedba2cb6052bfce461fa3f6b39d468287391db6fc46cb848347938bab3d5ff59a11f649e9ecf37ce641924018af8a1a4433f49e298910fd2da616ac31233f436076b691580d9ada615586ce75b72605473339b8e91574571d3d6633795dd73c1af96403491914f6eaa05ffdd4b36f8231a2eb5a5513024e4b3246ffb51641ebd3abc649739f4b608630e38bc1e1954ee7e1cb72c81dee79baa0f9c6cd6fa0e4e936c4b4d3a4c453f67aa43e45a85c1660b8728b83bbc494469355446bd07fe0ff87948efddf5bef5d8b1ec4bfa5e03053539874a9a7b

### Environment

``` python
{'sys.platform': 'linux',
 'Python': '3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]',
 'CUDA available': True,
 'numpy_random_seed': 2147483648,
 'GPU 0': 'NVIDIA TITAN RTX',
 'CUDA_HOME': '/usr/local/cuda',
 'NVCC': 'Cuda compilation tools, release 11.0, V11.0.194',
 'GCC': 'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0',
 'PyTorch': '1.8.2',
 'TorchVision': '0.9.2',
 'OpenCV': '4.7.0',
 'MMEngine': '0.7.3',
 'MMCV': '2.0.0rc4',
 'MMPreTrain': '1.0.0rc7+e80418a'}

```

**Comment by Ezra-Yu** [comment]
I try your image, and the result is OK. I am using the latest MMPreTrain, which was released last day. just the main branch.

Here is the result:

![image](https://github.com/open-mmlab/mmpretrain/assets/18586273/a11cf351-7116-47d8-9132-33c5eb459757)

**Comment by guneetmutreja** [comment]
@Ezra-Yu Thank you for the suggestions, updating to the latest version helped resolve the issue.

```python
'pred_label': 1,
'pred_score': 0.9496788382530212,
'pred_class': 'goldfish, Carassius auratus'}]
```
