### ISSUE TITLE
How to add validation loss curve  in training processing

### ISSUE THREAD

**Issue by sofpya** [open-mmlab/mmpretrain#1660]
### Branch

main branch (mmpretrain version)

### Describe the bug

there is no validation loss curve

### Environment

z

**Comment by Ezra-Yu** [comment]
Sorry, mmpretrain does not support that now.

**Comment by christianhi123** [comment]
Hello @Ezra-Yu do you know when this will be added or what do you suggest would be a good way to add this curve?
