### ISSUE TITLE
[Bug] The parameter computation in RandomCrop

### ISSUE THREAD

**Issue by haotianll** [open-mmlab/mmpretrain#1697]
### Branch

main branch (mmpretrain version)

### Describe the bug

There seems to be a small bug in the crop parameter computation in RandomCrop here:
https://github.com/open-mmlab/mmpretrain/blob/main/mmpretrain/datasets/transforms/processing.py#L172-L176

```python
if w == target_w and h == target_h:
    return 0, 0, h, w
elif w < target_w or h < target_h:
    target_w = min(w, target_w)
    target_h = min(w, target_h)
```
The ```target_h``` should base on ```h``` not ```w```.

### Bug Fix

Change the last line to:

```python
    target_h = min(h, target_h)
```

### Environment

For all environments.

**Comment by Ezra-Yu** [comment]
Yes. Thank you for your report, we will fix it soon.
