### ISSUE TITLE
[Bug] 'BEiTViT' object has no attribute 'pre_norm'

### ISSUE THREAD

**Issue by sun254667307** [open-mmlab/mmpretrain#1698]
### Branch

main branch (mmpretrain version)

### Describe the bug

We encounter this issue when running MiniGPT4

Traceback (most recent call last) 
│ /home/aaa/lib/python3.9/site-packages/mmengine/registry/build_functions.py:122 in build_from_cfg │
│                                                                                                  │
│   119 │   │   │   │   │   issubclass(obj_cls, ManagerMixin):  # type: ignore                     │
│   120 │   │   │   │   obj = obj_cls.get_instance(**args)  # type: ignore                         │
│   121 │   │   │   else:                                                                          │
│ ❱ 122 │   │   │   │   obj = obj_cls(**args)  # type: ignore                                      │
│   123 │   │   │                                                                                  │
│   124 │   │   │   if (inspect.isclass(obj_cls) or inspect.isfunction(obj_cls)                    │
│   125 │   │   │   │   │   or inspect.ismethod(obj_cls)):                                         │
│                                                                                                  │
│ /workspace/workgroup/mmpretrain/mmpretrain/models/backbones/beit.py:427 in         │
│ __init__                                                                                         │
│                                                                                                  │
│   424 │   │                                                                                      │
│   425 │   │   # freeze stages only when self.frozen_stages > 0                                   │
│   426 │   │   if self.frozen_stages > 0:                                                         │
│ ❱ 427 │   │   │   self._freeze_stages()                                                          │
│   428 │                                                                                          │
│   429 │   def forward(self, x):                                                                  │
│   430 │   │   B = x.shape[0]                                                                     │
│                                                                                                  │
│ /workspace/workgroup/mmpretrain/mmpretrain/models/backbones/vision_transformer.py: │
│ 436 in _freeze_stages                                                                            │
│                                                                                                  │
│   433 │   │   for param in self.patch_embed.parameters():                                        │
│   434 │   │   │   param.requires_grad = False                                                    │
│   435 │   │   # freeze pre-norm                                                                  │
│ ❱ 436 │   │   for param in self.pre_norm.parameters():                                           │
│   437 │   │   │   param.requires_grad = False                                                    │
│   438 │   │   # freeze cls_token                                                                 │
│   439 │   │   self.cls_token.requires_grad = False                                               │
│                                                                                                  │
│ /home/aaa/lib/python3.9/site-packages/torch/nn/modules/module.py:1207 in __getattr__             │
│                                                                                                  │
│   1204 │   │   │   modules = self.__dict__['_modules']                                           │
│   1205 │   │   │   if name in modules:                                                           │
│   1206 │   │   │   │   return modules[name]                                                      │
│ ❱ 1207 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
│   1208 │   │   │   type(self).__name__, name))                                                   │
│   1209 │                                                                                         │
│   1210 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:             │

AttributeError: 'BEiTViT' object has no attribute 'pre_norm'

### Environment

mmcv==2.0.1
mmcv-full==1.7.0
mmengine==0.8.0
mmpretrain==1.0.0
torch==1.12.1+cu113

**Comment by fangyixiao18** [comment]
Fixed in https://github.com/open-mmlab/mmpretrain/pull/1705, please use dev branch with newest code
