### ISSUE TITLE
[Bug] Why the architecture of ViT-s is different from the literature ?

### ISSUE THREAD

**Issue by fabien-merceron** [open-mmlab/mmpretrain#1713]
### Branch

main branch (mmpretrain version)

### Describe the bug

In the `arch_zoo` of the _[Vision Transformer](https://github.com/open-mmlab/mmpretrain/blob/ae7a7b75600923a7384b6c81e515626bf0a3ab4c/mmpretrain/models/backbones/vision_transformer.py#L173)_, why does ViT-S have 8 layers, 8 heads and an embedding dimension of 768, whereas in the literature, ViT-S has 12 layers, 6 heads and an embedding dimension of 384 ?

### Environment

{'sys.platform': 'linux',
 'Python': '3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0]',
 'CUDA available': True,
 'numpy_random_seed': 2147483648,
 'GPU 0,1,2,3': 'Tesla K80',
 'CUDA_HOME': '/root/miniconda3/envs/py10env',
 'NVCC': 'Cuda compilation tools, release 11.7, V11.7.99',
 'GCC': 'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0',
 'PyTorch': '1.13.1',
 'TorchVision': '0.14.1',
 'OpenCV': '4.7.0',
 'MMEngine': '0.8.1',
 'MMCV': '2.0.1',
 'MMPreTrain': '1.0.0+'}

**Comment by Ezra-Yu** [comment]
The original ViT paper does not contain architecture for Vit-S

> ViT-S has 12 layers, 6 heads and an embedding dimension of 384 

This is DeiT-s, which is included in https://github.com/open-mmlab/mmpretrain/blob/ae7a7b75600923a7384b6c81e515626bf0a3ab4c/mmpretrain/models/backbones/vision_transformer.py#L223


> why does ViT-S have 8 layers, 8 heads and an embedding dimension of 768,

It is a vit-s architecture from other implements of ViT, we have already forgotten which specific repo it was.

In a word, The original VIT paper did not include VIT-S, and various unofficial versions are available now.
