### ISSUE TITLE
[Bug] torchvision normalization and not inbuilt normalization

### ISSUE THREAD

**Issue by christianhi123** [open-mmlab/mmpretrain#1724]
### Branch

main branch (mmpretrain version)

### Describe the bug

Using a recipe with torchvision transforms and using torchvision's normalization and not the built-in with data_preprocessor, following error occurs:
cfg = Config.fromfile(args.config)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/config/config.py", line 179, in fromfile
    filename, use_predefined_variables, use_environment_variables)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/config/config.py", line 493, in _file2dict
    use_environment_variables=use_environment_variables)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/config/config.py", line 522, in _file2dict
    eval(codeobj, global_locals_var, global_locals_var)
  File "", line 19, in <module>
**_TypeError: 'NoneType' object is not subscriptable_**
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f7f4c0ba560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/opt/conda/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpzgzjrs_y/tmp1nyt5oaw.py'
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f7f4c0ba560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/opt/conda/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpnmk5l307/tmpqrcy9mrf.py'

___________________________________

I think this is due to mean=None and std=None. 

These were set in accordance to the tutorial outlined in https://mmpretrain.readthedocs.io/en/latest/api/data_process.html#torchvision-transforms

Section 2. Use TorchVision Augs and ToTensor&Normalize

### Environment

System environment:
    sys.platform: linux
    Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
    CUDA available: True
    numpy_random_seed: 42
    GPU 0: NVIDIA XXXXXXXXXXXX
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 11.3, V11.3.109
    GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    PyTorch: 1.12.1
    PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

    TorchVision: 0.13.1
    OpenCV: 4.7.0
    MMEngine: 0.7.4

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: 42
    deterministic: True
    Distributed launcher: none
    Distributed training: False
    GPU number: 1

### Other information

Environment built with provided DockerFile

data_preprocessor seems to use:

https://mmcv.readthedocs.io/en/latest/api/generated/mmcv.image.imnormalize.html#mmcv.image.imnormalize

I could set a PR to mmcv to include NoneType flags so it works in accordance to the tutorial, or is torchvision normalization not wished?

P.S. The link used in this bug report heading for PR creation is not up to dat anymore and leads to 
https://mmpretrain.readthedocs.io/en/master/community/CONTRIBUTING.html
instead of 
https://mmpretrain.readthedocs.io/en/latest/notes/contribution_guide.html

**Comment by Ezra-Yu** [comment]
Can you show me your config? 

```
File "/opt/conda/lib/python3.7/site-packages/mmengine/config/config.py", line 179, in fromfile
filename, use_predefined_variables, use_environment_variables)
File "/opt/conda/lib/python3.7/site-packages/mmengine/config/config.py", line 493, in _file2dict
use_environment_variables=use_environment_variables)
File "/opt/conda/lib/python3.7/site-packages/mmengine/config/config.py", line 522, in _file2dict
eval(codeobj, global_locals_var, global_locals_var)
File "", line 19, in
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function _TemporaryFileCloser.del at 0x7f7f4c0ba560>
Traceback (most recent call last):
File "/opt/conda/lib/python3.7/tempfile.py", line 448, in del
self.close()
File "/opt/conda/lib/python3.7/tempfile.py", line 444, in close
unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpzgzjrs_y/tmp1nyt5oaw.py'
Exception ignored in: <function _TemporaryFileCloser.del at 0x7f7f4c0ba560>
Traceback (most recent call last):
File "/opt/conda/lib/python3.7/tempfile.py", line 448, in del
self.close()
File "/opt/conda/lib/python3.7/tempfile.py", line 444, in close
unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpnmk5l307/tmpqrcy9mrf.py'
```

This error indicates that there is an grammatical error in your config.

**Comment by christianhi123** [comment]
Ok thank you for the guidance. Below is the important portion that leads to the error. Is it possibly because of the comments inside dictionary items?

```# dataset settings
dataset_type = 'CustomDataset'
data_preprocessor = dict(
    num_classes=80,
    # RGB format normalization parameters
    mean=None,
    std=None,
    # convert image from BGR to RGB
    # to_rgb=True,
    #When using torchvision annotations and normalizations
    to_rgb=False,
)
# Originals
# mean=[0.485, 0.456, 0.406],
# std=[0.229, 0.224, 0.225]

bgr_mean = data_preprocessor['mean'][::-1]
bgr_std = data_preprocessor['std'][::-1]

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='NumpyToPIL', to_rgb=True),       # from BGR in cv2 to RGB  in PIL
    dict(
        type='torchvision/Resize',
        size=(224,224),
        antialias=None),            # accept str format interpolation mode
    dict(type='torchvision/PILToTensor'),
    dict(type='torchvision/ConvertImageDtype', dtype=torch.float),
    dict(
        type='torchvision/Normalize',
        mean=(0.485, 0.456, 0.406),
        std=(0.229, 0.224, 0.225),
    ),
    dict(type='torchvision/RandomAutocontrast'),
    # When using no torchvision transforms
    # dict(type='Resize', scale=48),

    dict(type='PackInputs'),
]

# test_pipeline = [
#     dict(type='LoadImageFromFile'),
#     dict(type='Resize',scale=224),
#     dict(type='PackInputs'),
# ]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='NumpyToPIL', to_rgb=True),  # from BGR in cv2 to RGB  in PIL
    dict(
        type='torchvision/Resize',
        size=(224, 224),
        antialias=None),  # accept str format interpolation mode
    dict(type='torchvision/PILToTensor'),
    dict(type='torchvision/ConvertImageDtype', dtype=torch.float),
    dict(
        type='torchvision/Normalize',
        mean=(0.485, 0.456, 0.406),
        std=(0.229, 0.224, 0.225),
    ),
    dict(type='PackInputs'),
]```

**Comment by Ezra-Yu** [comment]
remove these two lines:
```
bgr_mean = data_preprocessor['mean'][::-1]
bgr_std = data_preprocessor['std'][::-1]
```

you can use mmengine API to check:
```
from mmengine.config import Config
cfg = Config.fromfile("./test.py")  # use the path of your config file
```

Sorry that this config grammatical error always makes users confused!  I will contact with MMEngine Team wether they can improve this error message.

**Comment by christianhi123** [comment]
Oh my god... that is a super simple fix and I overlooked this portion.

Well, the "not subscriptable" is logical that it refers to a list being used.

Thank you!!

**Comment by christianhi123** [comment]
Hello @Ezra-Yu I am still getting an error, not related to the list but the following:
```
cfg = Config.fromfile(args.config)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/config/config.py", line 179, in fromfile
    filename, use_predefined_variables, use_environment_variables)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/config/config.py", line 493, in _file2dict
    use_environment_variables=use_environment_variables)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/config/config.py", line 522, in _file2dict
    eval(codeobj, global_locals_var, global_locals_var)
  File "", line 18, in <module>
NameError: name 'torch' is not defined
```

This is the config now:

```
# dataset settings
dataset_type = 'CustomDataset'
data_preprocessor = dict(
    num_classes=31,
    mean=None,
    std=None,
    to_rgb=False,
)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='NumpyToPIL', to_rgb=True),       # from BGR in cv2 to RGB  in PIL
    dict(
        type='torchvision/Resize',
        size=(224,224),
        antialias=None),            # accept str format interpolation mode
    dict(type='torchvision/PILToTensor'),
    dict(type='torchvision/ConvertImageDtype', dtype=torch.float),
    dict(
        type='torchvision/Normalize',
        mean=(0.485, 0.456, 0.406),
        std=(0.229, 0.224, 0.225),
    ),
    dict(type='torchvision/RandomAutocontrast'),
    dict(type='PackInputs'),
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='NumpyToPIL', to_rgb=True),  # from BGR in cv2 to RGB  in PIL
    dict(
        type='torchvision/Resize',
        size=(224, 224),
        antialias=None),  # accept str format interpolation mode
    dict(type='torchvision/PILToTensor'),
    dict(type='torchvision/ConvertImageDtype', dtype=torch.float),
    dict(
        type='torchvision/Normalize',
        mean=(0.485, 0.456, 0.406),
        std=(0.229, 0.224, 0.225),
    ),
    dict(type='PackInputs'),
]

```

I hope you could support me here.
