### ISSUE TITLE
[Bug] image dataloader problem while using CustomDataset

### ISSUE THREAD

**Issue by FrancisChen888** [open-mmlab/mmpretrain#1768]
### Branch

main branch (mmpretrain version)

### Describe the bug

auto_scale_lr = dict(base_batch_size=32)
data_preprocessor = dict(
    mean=[
        123.675,
        116.28,
        103.53,
    ],
    num_classes=2,
    std=[
        58.395,
        57.12,
        57.375,
    ],
    to_rgb=True)
data_root = '/root/share/object_detection/data/classify'
dataset_type = 'CustomDataset'
default_hooks = dict(
    checkpoint=dict(interval=1, type='CheckpointHook'),
    logger=dict(interval=100, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(enable=False, type='VisualizationHook'))
default_scope = 'mmpretrain'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
launcher = 'none'
load_from = None
log_level = 'INFO'
model = dict(
    backbone=dict(
        arch='b7',
        init_cfg=dict(
            checkpoint=
            '/root/share/mmpretrain-main/pretrained/efficientnet-b7_3rdparty_8xb32-aa_in1k_20220119-bf03951c.pth',
            prefix='backbone',
            type='Pretrained'),
        type='EfficientNet'),
    head=dict(
        in_channels=2560,
        loss=dict(loss_weight=1.0, type='CrossEntropyLoss'),
        num_classes=2,
        topk=1,
        type='LinearClsHead'),
    neck=dict(type='GlobalAveragePooling'),
    type='ImageClassifier')
optim_wrapper = dict(
    optimizer=dict(lr=0.01, momentum=0.9, type='SGD', weight_decay=0.0001))
param_scheduler = dict(
    by_epoch=True, gamma=0.1, milestones=[
        15,
    ], type='MultiStepLR')
randomness = dict(deterministic=False, seed=None)
resume = False
test_cfg = dict()
test_dataloader = dict(
    batch_size=32,
    collate_fn=dict(type='default_collate'),
    dataset=dict(
        ann_file='',
        data_prefix='val',
        data_root='/root/share/object_detection/data/classify',
        type='CustomDataset',
        with_label=True),
    num_workers=8,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(topk=1, type='Accuracy')
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(crop_size=600, type='EfficientNetCenterCrop'),
    dict(type='PackInputs'),
]
train_cfg = dict(by_epoch=True, max_epochs=40, val_interval=1)
train_dataloader = dict(
    batch_size=32,
    collate_fn=dict(type='default_collate'),
    dataset=dict(
        ann_file='',
        data_prefix='train',
        data_root='/root/share/object_detection/data/classify',
        type='CustomDataset',
        with_label=True),
    num_workers=8,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(scale=600, type='EfficientNetRandomCrop'),
    dict(direction='horizontal', prob=0.5, type='RandomFlip'),
    dict(type='PackInputs'),
]
val_cfg = dict()
val_dataloader = dict(
    batch_size=32,
    collate_fn=dict(type='default_collate'),
    dataset=dict(
        ann_file='',
        data_prefix='val',
        data_root='/root/share/object_detection/data/classify',
        type='CustomDataset',
        with_label=True),
    num_workers=8,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(topk=1, type='Accuracy')
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    type='UniversalVisualizer', vis_backends=[
        dict(type='LocalVisBackend'),
    ])
work_dir = './work_dirs/efficientnet-b7_8xb32_customer'

08/16 16:21:25 - mmengine - INFO - Distributed training is not used, all SyncBatchNorm (SyncBN) layers in the model will be automatically reverted to BatchNormXd layers if they are used.
08/16 16:21:25 - mmengine - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) RuntimeInfoHook                    
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
before_train:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(NORMAL      ) DistSamplerSeedHook                
 -------------------- 
before_train_iter:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
 -------------------- 
after_train_iter:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
(LOW         ) ParamSchedulerHook                 
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) IterTimerHook                      
(LOW         ) ParamSchedulerHook                 
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
before_val:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
before_val_epoch:
(NORMAL      ) IterTimerHook                      
 -------------------- 
before_val_iter:
(NORMAL      ) IterTimerHook                      
 -------------------- 
after_val_iter:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) VisualizationHook                  
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
after_val_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
(LOW         ) ParamSchedulerHook                 
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
after_val:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
after_train:
(VERY_HIGH   ) RuntimeInfoHook                    
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
before_test:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
before_test_epoch:
(NORMAL      ) IterTimerHook                      
 -------------------- 
before_test_iter:
(NORMAL      ) IterTimerHook                      
 -------------------- 
after_test_iter:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) VisualizationHook                  
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
after_test_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
after_test:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
after_run:
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
08/16 16:21:26 - mmengine - INFO - load backbone in model from: /root/share/mmpretrain-main/pretrained/efficientnet-b7_3rdparty_8xb32-aa_in1k_20220119-bf03951c.pth
Loads checkpoint by local backend from path: /root/share/mmpretrain-main/pretrained/efficientnet-b7_3rdparty_8xb32-aa_in1k_20220119-bf03951c.pth
08/16 16:21:26 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
08/16 16:21:26 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
08/16 16:21:26 - mmengine - INFO - Checkpoints will be saved to /root/share/mmpretrain-main/work_dirs/efficientnet-b7_8xb32_customer.

Traceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 162, in main
    runner.train()
  File "/root/.local/conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "/root/.local/conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/root/.local/conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 113, in run_epoch
    self.run_iter(idx, data_batch)
  File "/root/.local/conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 129, in run_iter
    outputs = self.runner.model.train_step(
  File "/root/.local/conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 113, in train_step
    data = self.data_preprocessor(data, True)
  File "/root/.local/conda/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/share/mmpretrain-main/mmpretrain/models/utils/data_preprocessor.py", line 109, in forward
    inputs = self.cast_data(data['inputs'])
KeyError: 'inputs'

### Environment

System environment:
    sys.platform: linux
    Python: 3.8.17 (default, Jul  5 2023, 21:04:15) [GCC 11.2.0]
    CUDA available: True
    numpy_random_seed: 273804074
    GPU 0: Tesla V100S-PCIE-32GB
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 10.1, V10.1.24
    GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    PyTorch: 2.0.0
    PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

    TorchVision: 0.15.0
    OpenCV: 4.8.0
    MMEngine: 0.8.4

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: 273804074
    deterministic: False
    Distributed launcher: none
    Distributed training: False
    GPU number: 1
------------------------------------------------------------

### Other information

The data strucion is shown as following:
{'img_path': ['/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-11.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-593.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-335.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-297.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-271.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-386.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-140.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-533.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-363.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-292.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-130.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-192.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-469.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-99.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-56.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-468.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-176.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-74.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-377.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-683.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-580.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-569.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-713.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-392.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-438.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-666.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-694.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-609.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-207.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-185.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-641.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-640.jpg'],
 'gt_label': tensor([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
        1, 1, 0, 0, 1, 0, 1, 1]), 
'sample_idx': tensor([259, 182,  88, 357, 342, 399, 274, 479, 389, 355,  14,  47, 135, 588,
        496, 439, 286, 249, 395, 227, 506, 500, 564, 402, 425, 533, 232, 192,
        302,  45, 524, 523])}

**Comment by FrancisChen888** [comment]
inputs = self.cast_data(**data**['inputs'])
The **data** structure is shown as following and it's generate automatictly with the code in mmpretrain-main/mmpretrain/datasets/custom.py:
{'img_path': ['/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-11.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-593.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-335.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-297.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-271.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-386.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-140.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-533.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-363.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-292.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-130.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-192.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-469.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-99.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-56.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-468.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-176.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-74.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-377.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-683.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-580.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-569.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-713.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-392.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-438.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-666.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-694.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-609.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-207.jpg', '/root/share/object_detection/data/classify/train/images/bottom_rubbish-185.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-641.jpg', '/root/share/object_detection/data/classify/train/no_labels/bottom_rubbish-640.jpg'],
'gt_label': tensor([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
1, 1, 0, 0, 1, 0, 1, 1]),
'sample_idx': tensor([259, 182, 88, 357, 342, 399, 274, 479, 389, 355, 14, 47, 135, 588,
496, 439, 286, 249, 395, 227, 506, 500, 564, 402, 425, 533, 232, 192,
302, 45, 524, 523])}

**Comment by gmy1210** [comment]
we have the same problem, how did you fix it?
