### ISSUE TITLE
[Feature] Support for pretaining convnext-v2

### ISSUE THREAD

**Issue by chaoer** [open-mmlab/mmpretrain#1871]
### Describe the feature

Is there any support for pretraining configs for convnext-v2?

**Comment by xiaoerjason** [comment]
I'm not sure if I need to read this URL: https://mmpretrain.readthedocs.io/en/latest/papers/convnext_v2.html

**Comment by chaoer** [comment]
> I'm not sure if I need to read this URL: https://mmpretrain.readthedocs.io/en/latest/papers/convnext_v2.html

Thanks, that's it

**Comment by goldwater668** [comment]
@xiaoerjason If you use the official Facebook code for fcma pre-training, how to convert it into a configuration and model that can be used by mmpretrain? https://mmpretrain.readthedocs.io/en/latest/papers/convnext_v2.html

**Comment by xiaoerjason** [comment]
@goldwater668 The official FCMA pre trained model cannot be directly used in MMPRetrain because their model configurations are different.

**Comment by goldwater668** [comment]
> @goldwater668官方的FCMA预训练模型不能直接在MMPRetrain中使用，因为它们的模型配置不同。

How should I convert it? I think you also converted it through the official method.
