### ISSUE TITLE
DINOv2 training

### ISSUE THREAD

**Issue by LichunZhang** [open-mmlab/mmpretrain#1890]
### Describe the feature

Although it says DINOv2 backbone is supported, only the inference of the teacher backbone is provided. It would be great if you include the whole training pipeline of DINOv2.

### Will you implement it?

- [ ] I would like to implement this feature and create a PR!

**Comment by ayushnangia** [comment]
hey did you find the dinov2 pretraining pipeline? @LichunZhang
